import React, { useState, useEffect } from 'react';
import './PayslipsList.css';

const PayslipsList = ({ userEmail, limit = 3 }) => {
  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadPayslips();
  }, [userEmail]);

  const loadPayslips = async () => {
    try {
      setLoading(true);
      
      // Try to get payslips from backend first
      try {
        const response = await fetch(`/api/payslip/employee/${userEmail}`, {
          headers: {
            'Authorization': `Bearer ${localStorage.getItem('token')}`
          }
        });
        
        if (response.ok) {
          const backendPayslips = await response.json();
          setPayslips(backendPayslips.slice(0, limit));
          return;
        }
      } catch (error) {
        console.log('Backend payslips not available, using local storage');
      }
      
      // Fallback to localStorage
      const localPayslips = JSON.parse(localStorage.getItem('payslips') || '[]');
      const userPayslips = localPayslips
        .filter(p => p.employeeEmail === userEmail)
        .sort((a, b) => new Date(b.generatedAt) - new Date(a.generatedAt))
        .slice(0, limit);
      
      setPayslips(userPayslips);
    } catch (error) {
      console.error('Error loading payslips:', error);
    } finally {
      setLoading(false);
    }
  };

  const downloadPayslip = (payslip) => {
    const content = `PAYSLIP
Employee: ${payslip.employeeName}
Email: ${payslip.employeeEmail}
Month: ${payslip.month}/${payslip.year}
Basic Salary: ₹${payslip.basicSalary?.toLocaleString('en-IN')}
Allowances: ₹${payslip.allowances?.toLocaleString('en-IN')}
Deductions: ₹${payslip.deductions?.toLocaleString('en-IN')}
Net Salary: ₹${payslip.netSalary?.toLocaleString('en-IN')}
Working Days: ${payslip.workingDays}/${payslip.totalDays}
Status: ${payslip.status}
Generated: ${new Date(payslip.generatedAt).toLocaleDateString()}`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `payslip_${payslip.employeeName}_${payslip.month}_${payslip.year}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="payslips-loading">
        <p>Loading payslips...</p>
      </div>
    );
  }

  if (payslips.length === 0) {
    return (
      <div className="no-payslips">
        <div className="no-payslips-icon">📄</div>
        <p>No payslips available yet</p>
        <small>Payslips will appear here once they are generated by your admin</small>
      </div>
    );
  }

  return (
    <div className="payslips-list">
      {payslips.map((payslip) => (
        <div key={payslip.id} className="payslip-item">
          <div className="payslip-info">
            <div className="payslip-month">
              {payslip.month}/{payslip.year}
            </div>
            <div className="payslip-amount">
              ₹{payslip.netSalary?.toLocaleString('en-IN')}
            </div>
            <div className="payslip-status">
              {payslip.status}
            </div>
          </div>
          <div className="payslip-actions">
            <button 
              className="download-btn"
              onClick={() => downloadPayslip(payslip)}
              title="Download payslip"
            >
              📄 Download
            </button>
          </div>
        </div>
      ))}
    </div>
  );
};

export default PayslipsList;
