import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import './Payslips.css';

const Payslips = () => {
  const location = useLocation();
  const [user, setUser] = useState(null);
  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const userData = JSON.parse(localStorage.getItem('user') || '{}');
    setUser(userData);
    
    if (userData?.email) {
      loadPayslips(userData.email);
    }
  }, []);

  const loadPayslips = async (email) => {
    try {
      setLoading(true);
      
      // Try to get payslips from backend first
      try {
        const response = await fetch(`/api/payslip/employee/${email}`, {
          headers: {
            'Authorization': `Bearer ${localStorage.getItem('token')}`
          }
        });
        
        if (response.ok) {
          const backendPayslips = await response.json();
          setPayslips(backendPayslips);
          return;
        }
      } catch (error) {
        console.log('Backend payslips not available, using local storage');
      }
      
      // Fallback to localStorage
      const localPayslips = JSON.parse(localStorage.getItem('payslips') || '[]');
      const userPayslips = localPayslips
        .filter(p => p.employeeEmail === email)
        .sort((a, b) => new Date(b.generatedAt) - new Date(a.generatedAt));
      
      setPayslips(userPayslips);
    } catch (error) {
      console.error('Error loading payslips:', error);
    } finally {
      setLoading(false);
    }
  };

  const downloadPayslip = (payslip) => {
    const content = `PAYSLIP
Employee: ${payslip.employeeName}
Email: ${payslip.employeeEmail}
Month: ${payslip.month}/${payslip.year}
Basic Salary: ₹${payslip.basicSalary?.toLocaleString('en-IN')}
Allowances: ₹${payslip.allowances?.toLocaleString('en-IN')}
Deductions: ₹${payslip.deductions?.toLocaleString('en-IN')}
Net Salary: ₹${payslip.netSalary?.toLocaleString('en-IN')}
Working Days: ${payslip.workingDays}/${payslip.totalDays}
Status: ${payslip.status}
Generated: ${new Date(payslip.generatedAt).toLocaleDateString()}`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `payslip_${payslip.employeeName}_${payslip.month}_${payslip.year}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'generated': return '#10b981';
      case 'paid': return '#3b82f6';
      case 'pending': return '#f59e0b';
      default: return '#6b7280';
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'generated': return '📄';
      case 'paid': return '✅';
      case 'pending': return '⏳';
      default: return '❓';
    }
  };

  if (!user) {
    return (
      <div className="payslips-container">
        <div className="loading">Loading...</div>
      </div>
    );
  }

  return (
    <div className="payslips-container">
      <div className="payslips-header">
        <h1>My Payslips</h1>
        <p>View and download your salary payslips</p>
      </div>

      <div className="payslips-content">
        {loading ? (
          <div className="loading">
            <div className="loading-spinner"></div>
            <p>Loading payslips...</p>
          </div>
        ) : payslips.length === 0 ? (
          <div className="no-payslips">
            <div className="no-payslips-icon">💰</div>
            <h3>No Payslips Available</h3>
            <p>Your payslips will appear here once they are generated by your admin.</p>
            <small>Payslips are typically generated monthly after KYC approval.</small>
          </div>
        ) : (
          <div className="payslips-grid">
            {payslips.map((payslip) => (
              <div key={payslip.id} className="payslip-card">
                <div className="payslip-header">
                  <div className="payslip-month">
                    {payslip.month}/{payslip.year}
                  </div>
                  <div 
                    className="payslip-status"
                    style={{ color: getStatusColor(payslip.status) }}
                  >
                    {getStatusIcon(payslip.status)} {payslip.status}
                  </div>
                </div>
                
                <div className="payslip-amount">
                  ₹{payslip.netSalary?.toLocaleString('en-IN')}
                </div>
                
                <div className="payslip-details">
                  <div className="detail-row">
                    <span className="label">Basic Salary:</span>
                    <span className="value">₹{payslip.basicSalary?.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="detail-row">
                    <span className="label">Allowances:</span>
                    <span className="value">₹{payslip.allowances?.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="detail-row">
                    <span className="label">Deductions:</span>
                    <span className="value">₹{payslip.deductions?.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="detail-row">
                    <span className="label">Working Days:</span>
                    <span className="value">{payslip.workingDays}/{payslip.totalDays}</span>
                  </div>
                </div>
                
                <div className="payslip-footer">
                  <div className="generated-date">
                    Generated: {new Date(payslip.generatedAt).toLocaleDateString()}
                  </div>
                  <button 
                    className="download-btn"
                    onClick={() => downloadPayslip(payslip)}
                    title="Download payslip"
                  >
                    📄 Download
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Payslips;